import { createApp } from 'vue'
import './assets/css/variables.css'
import './assets/css/base.css'
import './assets/css/utilities.css'
import './assets/css/stars.css'
import './assets/css/nav.css'
import './assets/css/hero.css'
import './assets/css/pain.css'
import './assets/css/values.css'
import './assets/css/trust.css'
import './assets/css/pricing.css'
import './assets/css/faq.css'
import './assets/css/cta.css'
import './assets/css/footer.css'
import './assets/css/back-to-top.css'
import './assets/css/responsive.css'
import './assets/css/animations.css'
import App from './App.vue'
import router from './router'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'

createApp(App).use(router).use(ElementPlus).mount('#app')
